test "json storage cache":
    set {_json} to json from "{array: [{A: 1, B: 2, C: 3, location: {}}]}"

    create json file "jsons/test.json" and write to it {_json} with configuration[replace=true, encoding=UTF-8]

    create json virtual storage named "virtual"

    set (json storage of id "virtual").new to "Test"

    bind json file "jsons/test.json" as "test"

    set {_j1} to json storage of id "virtual"
    set {_j2} to json storage of id "test"

    assert {_j1} is set with "failing: cannot create virtual storage"
    assert {_j2} is set with "failing: cannot create an cache from file"