test "json loop":
    set {_json} to json from "{data: [{special: [1, 2, 3], player: 2}]}"

    loop values of {_json}:
        broadcast "&aKEY-1: %json-key-1%"
        assert "%json-key-1%" is "data" with "failing: cannot loop through json object"
        if json-value-1 is json element:

            assert "%json-value-1[0].special%" is "[1,2,3]" with "failing: cannot loop through json object"

            set {_json-list::*} to json-value-1[0].special*

            broadcast "%{_json-list::*}%" 

            assert "%(json-value-1[0].special*)%" is "1, 2 and 3" with "failing: cannot loop through json object with *"


            loop values of json-value-1:
                assert "%json-value-2%" is "{""special"":[1,2,3],""player"":2}" with "failing: cannot loop through json array"
                set {_list::*} to values "special" of json-value-2
                broadcast "%{_list::*}%"
                assert {_list::*} is 1, 2 and 3 with "failing: cannot loop through json array"